name: Rails CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
    - name: Install dependencies
      run: bundle install
    # - name: Set up Database
    #   run: bin/rails db:create db:migrate RAILS_ENV=test
    - name: Run tests
      run: bundle exec rspec
